# Generated by Django 3.2.3 on 2021-07-12 14:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import main.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_auto_20210602_0601'), ('main', '0003_auto_20210603_0500'), ('main', '0004_auto_20210603_0511'), ('main', '0005_profile'), ('main', '0006_auto_20210606_1658'), ('main', '0007_alter_profile_img'), ('main', '0008_alter_profile_img'), ('main', '0009_alter_profile_img'), ('main', '0010_alter_profile_img'), ('main', '0011_alter_profile_img'), ('main', '0012_auto_20210607_1619'), ('main', '0013_picture_test_field'), ('main', '0014_alter_profile_birthday'), ('main', '0015_auto_20210610_0842'), ('main', '0016_subscriber'), ('main', '0017_auto_20210614_1840'), ('main', '0018_profile_phone_number'), ('main', '0019_smslog'), ('main', '0020_alter_profile_phone_number'), ('main', '0021_alter_car_type_fuel'), ('main', '0022_auto_20210629_0516'), ('main', '0023_auto_20210705_0625'), ('main', '0024_auto_20210706_1334'), ('main', '0025_auto_20210706_1336'), ('main', '0026_delete_tag')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fuel', models.CharField(blank=True, default=None, max_length=24, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('duration', models.DateTimeField()),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('publication', models.BooleanField(default=True)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdArchive',
            fields=[
            ],
            options={
                'ordering': ['created_date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.services',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('engine_volume', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('type_fuel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.typefuel')),
                ('publication', models.BooleanField(default=True)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(blank=True, default='img_html/default.jpg', upload_to='img_html')),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car')),
                ('test_field', models.CharField(default='test picture words', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_numer', models.CharField(max_length=5)),
                ('message_sid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('birthday', models.DateField(max_length=8, validators=[main.models.validate_birthday])),
                ('img', sorl.thumbnail.fields.ImageField(blank=True, default='img_html/default.jpg', upload_to='img_html')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='profile',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('price', models.PositiveIntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_new', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('publication', models.BooleanField(default=True)),
                ('tag', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
