# Generated by Django 3.2.3 on 2021-06-02 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_car_sellers_ads', to='main.seller', verbose_name='продавец'),
        ),
        migrations.AddField(
            model_name='services',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_services_sellers_ads', to='main.seller', verbose_name='продавец'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_stuff_sellers_ads', to='main.seller', verbose_name='продавец'),
        ),
    ]
