# Generated by Django 3.2.3 on 2021-06-03 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210602_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='tag',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddField(
            model_name='services',
            name='tag',
            field=models.ManyToManyField(to='main.Tag'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='tag',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
