# Generated by Django 3.2.3 on 2021-06-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210603_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='main_car_ads', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='main_services_ads', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='main_stuff_ads', to='main.Tag'),
        ),
    ]
