# Generated by Django 3.2.3 on 2021-05-30 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210530_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdArchive',
            fields=[
            ],
            options={
                'ordering': ['created_date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.ad',),
        ),
    ]
