# Generated by Django 3.2.3 on 2021-06-06 16:58

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ('first_name',), 'verbose_name': 'Seller', 'verbose_name_plural': 'Sellers'},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='../static/admin/img/img_html'),
        ),
    ]
