# Generated by Django 3.2.3 on 2021-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_adarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
