# Generated by Django 3.2.3 on 2021-06-06 17:02

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210606_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='../img'),
        ),
    ]
