# Generated by Django 3.2.3 on 2021-06-06 17:21

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to='img/img_html'),
        ),
    ]
