# Generated by Django 3.2.3 on 2021-06-07 11:17

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='img_html/default.jpg', upload_to='img_html'),
        ),
    ]
