# Generated by Django 3.2.3 on 2021-06-07 16:19

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='main_car_ads', related_query_name='main_cars', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='services',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='main_services_ads', related_query_name='main_servicess', to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='main_stuff_ads', related_query_name='main_stuffs', to='main.Tag'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', sorl.thumbnail.fields.ImageField(blank=True, default='img_html/default.jpg', upload_to='img_html')),
                ('car', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.car')),
            ],
        ),
    ]
