# Generated by Django 3.2.3 on 2021-06-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210607_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='test_field',
            field=models.CharField(default='test picture words', max_length=100),
        ),
    ]
