# Generated by Django 3.2.3 on 2021-06-08 16:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_picture_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(max_length=8, validators=[main.models.validate_birthday]),
        ),
    ]
