# Generated by Django 3.2.3 on 2021-06-10 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_profile_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stuff',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
