# Generated by Django 3.2.3 on 2021-06-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_numer', models.CharField(max_length=5)),
                ('message_sid', models.TextField()),
            ],
        ),
    ]
