# Generated by Django 3.2.3 on 2021-07-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210629_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='publication',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='publication',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stuff',
            name='publication',
            field=models.BooleanField(default=True),
        ),
    ]
