# Generated by Django 3.2.3 on 2021-07-06 13:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210705_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='tag',
        ),
        migrations.AddField(
            model_name='car',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[1, 2], size=None),
        ),
        migrations.RemoveField(
            model_name='services',
            name='tag',
        ),
        migrations.AddField(
            model_name='services',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[1, 2], size=None),
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='tag',
        ),
        migrations.AddField(
            model_name='stuff',
            name='tag',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[1, 2], size=None),
        ),
    ]
